### PR TITLE
sync with airbnb

### PR DESCRIPTION
**Pull request by waroo**
#### Reasoning

_Please react with 👍/👎 if you agree or disagree with this proposal._

### CODE REVIEW

**Comment by Halle** [comment]
I 👍 all of this except for `"c60d1f6 Include a single space in a set of empty braces (`{ }`) (#167)"` which I'm neutral about, but don't object to.

**Review by Halle — APPROVED** [review]
👍

**Comment by waroo** [comment]
@Halle Can you resolve the conflicts and merge.  The single space in empty brackets should be fine, it doesn't happen often.

**Comment by Halle** [comment]
No problem, but could you first check out my concern I raised in the related story?

**Comment by Halle** [comment]
Resolved, edited for compatibility with our toolchain, and merged.

**Pull request merged**
